language: node_js
node_js:
  - "node"
before_install:
- npm install -g npm@latest
- npm install -g greenkeeper-lockfile@latest
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
after_success: npm run coverage
