language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
- 'node'
- '7'
- '6'
before_install:
- npm install -g npm@latest
- npm install -g greenkeeper-lockfile@1
before_script:
- npm prune
- greenkeeper-lockfile-update
install: npm install
after_script: greenkeeper-lockfile-upload
after_success:
- npm run coverage:upload
- npm run semantic-release
branches:
  except:
  - /^v\d+\.\d+\.\d+$/
